include("${SourceRoot}/cmake/MapRuntimeSources.cmake")
if(DEFINED FailureCase)
    noven_map_runtime_sources("${FixtureRoot}" selected)
    return()
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(root "$ENV{TEMP}/noven-map-install-${suffix}")
file(MAKE_DIRECTORY "${root}/data/pve" "${root}/maps/sources")
file(WRITE "${root}/data/map_compositions.tsv" "outputPath\tsourcePath\nmaps/test/preview.png\tmaps/sources/aa.png\nmaps/test/preview.png\tmaps/sources/aa.png\n")
file(WRITE "${root}/data/map_update_assets.tsv" "relativePath\turl\nmaps/sources/bb.png\thttps://assets.tarkov.dev/maps/test.png\n")
file(WRITE "${root}/data/map_floors.tsv" "mapId\tabstractPath\tsatellitePath\nmap1\tmaps/test/preview.png\t\n")
file(WRITE "${root}/data/pve/map_floors.tsv" "mapId\tabstractPath\tsatellitePath\nmap2\tmaps/sources/cc.png\t\n")
foreach(name aa bb cc unreferenced)
    file(WRITE "${root}/maps/sources/${name}.png" "fixture")
endforeach()
file(WRITE "${root}/maps/all.manifest.json" "{\"provenanceOnly\":\"maps/sources/unreferenced.png\"}")
noven_map_runtime_sources("${root}" selected)
if(NOT selected STREQUAL "maps/sources/aa.png;maps/sources/bb.png;maps/sources/cc.png")
    message(FATAL_ERROR "Selection must preserve recipe/update/PvE display dependencies, deduplicate and omit ledger-only inputs")
endif()
file(REMOVE "${root}/maps/sources/aa.png")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DSourceRoot=${SourceRoot}" "-DFixtureRoot=${root}" -DFailureCase=missing -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Missing runtime source accepted")
endif()
file(WRITE "${root}/maps/sources/aa.png" "fixture")
file(APPEND "${root}/data/map_update_assets.tsv" "maps/sources/../escape.png\thttps://assets.tarkov.dev/maps/test.png\n")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DSourceRoot=${SourceRoot}" "-DFixtureRoot=${root}" -DFailureCase=unsafe -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Unsafe source path accepted")
endif()
# 只移除本测试创建的随机 Temp 子目录。
# Remove only this test's random temporary child.
file(REMOVE_RECURSE "${root}")
noven_map_runtime_sources("${SourceRoot}/assets" production)
list(LENGTH production count)
message(STATUS "Map runtime source selection PASS: ${count} production sources; no regeneration-only ledger inputs")
