# 仅打包显示/重拼/更新表引用的原始 PNG；来源账本不是运行依赖。
# Ship raw PNGs referenced by display/recomposition/update tables, not every provenance-ledger input.
function(noven_map_runtime_sources assets output)
    set(selected)
    foreach(table data/map_compositions.tsv data/map_update_assets.tsv data/map_floors.tsv data/pve/map_floors.tsv)
        set(path "${assets}/${table}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Missing runtime map table: ${table}")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
        file(STRINGS "${path}" rows ENCODING UTF-8 REGEX "maps/sources/")
        # TSV 的完整字段：分隔符为 tab，CMake 行列表分隔符为分号。
        # Match whole TSV fields separated by tabs or the CMake row-list separator.
        string(REGEX MATCHALL "(^|[\t;])maps/sources/[^\t;]+" fields "${rows}")
        list(TRANSFORM fields REPLACE "^[\t;]" "")
        list(APPEND selected ${fields})
    endforeach()
    list(REMOVE_DUPLICATES selected)
    list(SORT selected)
    foreach(field IN LISTS selected)
        if(NOT field MATCHES "^maps/sources/[a-f0-9]+\\.png$")
            message(FATAL_ERROR "Unsafe runtime map source: ${field}")
        endif()
        if(NOT EXISTS "${assets}/${field}" OR IS_DIRECTORY "${assets}/${field}")
            message(FATAL_ERROR "Missing runtime map source: ${field}")
        endif()
    endforeach()
    set(${output} "${selected}" PARENT_SCOPE)
endfunction()
